### ISSUE TITLE
[BUG] Dask and nvdashboard Jupyter Lab extentions are not working

### ISSUE THREAD

**Issue by jacobtomlinson** [rapidsai/build#43]
**Describe the bug**
When running the latest docker images the Dask and nvdashboard Jupyter Lab extensions do not display.

**Steps/Code to reproduce bug**

```
docker run -p 8888:8888 --rm -it rapidsai/rapidsai-nightly:cuda10.0-runtime-ubuntu16.04 bash
```

Then visit https://host:8888. Neither extensions will be available from the sidebar.

Running `conda upgrade jupyterlab` which updates to `1.2.3` and restarting Jupyter Lab seems to resolve this issue.

However once upgraded pynvml (needed for nvdashboard) appears to be missing some dependencies.

```
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.6/site-packages/jupyterlab_nvdashboard/server.py", line 7, in <module>
    from jupyterlab_nvdashboard import apps
  File "/opt/conda/envs/rapids/lib/python3.6/site-packages/jupyterlab_nvdashboard/apps/__init__.py", line 2, in <module>
    from . import gpu
  File "/opt/conda/envs/rapids/lib/python3.6/site-packages/jupyterlab_nvdashboard/apps/gpu.py", line 17, in <module>
    pynvml.nvmlInit()
  File "/opt/conda/envs/rapids/lib/python3.6/site-packages/pynvml/nvml.py", line 742, in nvmlInit
    _load_nvml_library()
  File "/opt/conda/envs/rapids/lib/python3.6/site-packages/pynvml/nvml.py", line 736, in _load_nvml_library
    check_return(NVML_ERROR_LIBRARY_NOT_FOUND)
  File "/opt/conda/envs/rapids/lib/python3.6/site-packages/pynvml/nvml.py", line 366, in check_return
    raise NVMLError(ret)
pynvml.nvml.NVMLError_LibraryNotFound: NVML Shared Library Not Found
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.6/site-packages/pynvml/nvml.py", line 734, in _load_nvml_library
    nvml_lib = CDLL("libnvidia-ml.so.1")
  File "/opt/conda/envs/rapids/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libnvidia-ml.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.6/site-packages/jupyterlab_nvdashboard/server.py", line 7, in <module>
    from jupyterlab_nvdashboard import apps
  File "/opt/conda/envs/rapids/lib/python3.6/site-packages/jupyterlab_nvdashboard/apps/__init__.py", line 2, in <module>
    from . import gpu
  File "/opt/conda/envs/rapids/lib/python3.6/site-packages/jupyterlab_nvdashboard/apps/gpu.py", line 17, in <module>
    pynvml.nvmlInit()
  File "/opt/conda/envs/rapids/lib/python3.6/site-packages/pynvml/nvml.py", line 742, in nvmlInit
    _load_nvml_library()
  File "/opt/conda/envs/rapids/lib/python3.6/site-packages/pynvml/nvml.py", line 736, in _load_nvml_library
    check_return(NVML_ERROR_LIBRARY_NOT_FOUND)
  File "/opt/conda/envs/rapids/lib/python3.6/site-packages/pynvml/nvml.py", line 366, in check_return
    raise NVMLError(ret)
pynvml.nvml.NVMLError_LibraryNotFound: NVML Shared Library Not Found
```

**Expected behavior**
Both extensions should be available in Jupyter Lab.

**Environment details (please complete the following information):**
 - Docker `rapidsai/rapidsai-nightly:cuda10.0-runtime-ubuntu16.04`

**Comment by kkraus14** [comment]
@jacobtomlinson are you running your docker container with the nvidia runtime? If you don't I imagine the nvml shared library won't necessarily be passed through as it's a part of the driver. You can try using `nvidia-smi` as a test.

**Comment by jacobtomlinson** [comment]
Ah good point. I likely wasn't using that in this quick test.

However the primary issue of the packaged version of Jupyter Lab being too old for the extensions still stands.

**Comment by ayushdg** [comment]
I have noticed this before and rebuilding Jupyter lab `jupyter lab build` and refreshing the page seemed to fix the issue. 
Note: Tested with 0.11 nightly, jupyterlab version 1.0.7

**Comment by jacobtomlinson** [comment]
Jupyter Lab will need to be >1.0 too I think

**Comment by vilmara** [comment]
Hi all, I am using the docker image `rapidsai/rapidsai:0.10-cuda10.1-runtime-ubuntu18.04`, I thought NVDashborad was installed by default; however, in order to have the "GPU DASHBOARD" menu enable I needed to run the extra installation within the docker:
```
$ pip install jupyterlab-nvdashboard
$ jupyter labextension install jupyterlab-nvdashboard
```

**Comment by rlratzel** [comment]
@jacobtomlinson is there a preferred version of `jupyterlab` that should be used, or is it okay to just get the latest?

**Comment by jacobtomlinson** [comment]
Anything recent and `>1.0` should be fine. Probably best to just go with latest. Thanks!

**Comment by rlratzel** [comment]
I reproduced this locally, updated the Dockerfile(s) to unpin `jupyterlab` and get the latest compatible (`1.2.4` in this case), re-ran and saw the extensions working.

I've committed the changes (to `branch-0.12`) and the Docker images are rebuilding now.

**Comment by jacobtomlinson** [comment]
Thanks @rlratzel!

**Comment by rlratzel** [comment]
@jacobtomlinson I tested this interactively using jupyterlab and my browser - do you have any suggestions on how I might add a test to our nightly runs in order to catch problems like this sooner?

**Comment by jacobtomlinson** [comment]
I can't think of a straight forward way of testing something like that. I'll ping some Jupyter folks for advice.

**Comment by jacobtomlinson** [comment]
@ian-r-rose do you have any quick thoughts on how we could test that a JLab extension installed correctly? Something a little more automated than opening the browser and looking.

**Comment by ian-r-rose** [comment]
Hmm, there is always `jupyter labextension list`, but that wouldn't necessarily catch runtime errors. If you really wanted to check that the extension shows up, you could try to open the page with something like Chrome headless/puppeteer and try to grab a DOM element from either of the extensions. I haven't really tried that though, so I don't know how easy it would be to set up.

**Comment by jacobtomlinson** [comment]
Ok thanks @ian-r-rose !
